baseURL = "https://kkmarf.github.io/"
languageCode = "zh-cn"
title = "kkMarf Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 10
